// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmvsvhssxijkmrmnqkdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdnN2aHNzeGlqa21ybW5xa2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTczMjcsImV4cCI6MjA2MzY5MzMyN30.o57564GpN5MQm3KSzav9lTd29uw9JzFsMyme4ZUjrkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);